# Generated by Django 4.0.4 on 2022-05-31 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=128, verbose_name='адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание пункта выдачи')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='тип продукта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64, verbose_name='название товара')),
                ('delivery_date', models.DateField(blank=True, verbose_name='дата доставки')),
                ('file', models.FileField(upload_to='delivery_files', verbose_name='файл')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='delivery.deliverypoint', verbose_name='пункт выдачи')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='delivery.producttype', verbose_name='тип товара')),
            ],
        ),
    ]
