# Generated by Django 4.0.4 on 2022-06-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='file',
            field=models.FileField(blank=True, upload_to='delivery_files', verbose_name='файл'),
        ),
    ]
